INSERT INTO countries (num_code, alpha_2_code, alpha_3_code, en_short_name, nationality, capital, region, currency_code, language_code, flag_url, dialling_code) VALUES
('004', 'AF', 'AFG', 'Afghanistan', 'Afghan', 'Kabul', 'AS', 'AFN', 'ps', 'https://restcountries.eu/data/afg.svg', '+93'),
('008', 'AL', 'ALB', 'Albania', 'Albanian', 'Tirana', 'EU', 'ALL', 'sq', 'https://restcountries.eu/data/alb.svg', '+355'),
('012', 'DZ', 'DZA', 'Algeria', 'Algerian', 'Algiers', 'AF', 'DZD', 'ar', 'https://restcountries.eu/data/dza.svg', '+213'),
('016', 'AS', 'ASM', 'American Samoa', 'American Samoan', 'Pago Pago', 'OC', 'USD', 'en', 'https://restcountries.eu/data/asm.svg', '+1684'),
('020', 'AD', 'AND', 'Andorra', 'Andorran', 'Andorra la Vella', 'EU', 'EUR', 'ca', 'https://restcountries.eu/data/and.svg', '+376'),
('024', 'AO', 'AGO', 'Angola', 'Angolan', 'Luanda', 'AF', 'AOA', 'pt', 'https://restcountries.eu/data/ago.svg', '+244'),
('028', 'AG', 'ATG', 'Antigua and Barbuda', 'Antiguan, Barbudan', 'Saint John''s', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/atg.svg', '+1268'),
('032', 'AR', 'ARG', 'Argentina', 'Argentine', 'Buenos Aires', 'SA', 'ARS', 'es', 'https://restcountries.eu/data/arg.svg', '+54'),
('051', 'AM', 'ARM', 'Armenia', 'Armenian', 'Yerevan', 'AS', 'AMD', 'hy', 'https://restcountries.eu/data/arm.svg', '+374'),
('036', 'AU', 'AUS', 'Australia', 'Australian', 'Canberra', 'OC', 'AUD', 'en', 'https://restcountries.eu/data/aus.svg', '+61'),
('040', 'AT', 'AUT', 'Austria', 'Austrian', 'Vienna', 'EU', 'EUR', 'de', 'https://restcountries.eu/data/aut.svg', '+43'),
('031', 'AZ', 'AZE', 'Azerbaijan', 'Azerbaijani', 'Baku', 'AS', 'AZN', 'az', 'https://restcountries.eu/data/aze.svg', '+994'),
('044', 'BS', 'BHS', 'Bahamas', 'Bahamian', 'Nassau', 'NA', 'BSD', 'en', 'https://restcountries.eu/data/bhs.svg', '+1242'),
('048', 'BH', 'BHR', 'Bahrain', 'Bahraini', 'Manama', 'AS', 'BHD', 'ar', 'https://restcountries.eu/data/bhr.svg', '+973'),
('050', 'BD', 'BGD', 'Bangladesh', 'Bangladeshi', 'Dhaka', 'AS', 'BDT', 'bn', 'https://restcountries.eu/data/bgd.svg', '+880'),
('052', 'BB', 'BRB', 'Barbados', 'Barbadian', 'Bridgetown', 'NA', 'BBD', 'en', 'https://restcountries.eu/data/brb.svg', '+1246'),
('112', 'BY', 'BLR', 'Belarus', 'Belarusian', 'Minsk', 'EU', 'BYN', 'be', 'https://restcountries.eu/data/blr.svg', '+375'),
('056', 'BE', 'BEL', 'Belgium', 'Belgian', 'Brussels', 'EU', 'EUR', 'nl', 'https://restcountries.eu/data/bel.svg', '+32'),
('084', 'BZ', 'BLZ', 'Belize', 'Belizean', 'Belmopan', 'NA', 'BZD', 'en', 'https://restcountries.eu/data/blz.svg', '+501'),
('204', 'BJ', 'BEN', 'Benin', 'Beninese', 'Porto-Novo', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/ben.svg', '+229'),
('060', 'BM', 'BMU', 'Bermuda', 'Bermudian', 'Hamilton', 'NA', 'BMD', 'en', 'https://restcountries.eu/data/bmu.svg', '+1441'),
('064', 'BT', 'BTN', 'Bhutan', 'Bhutanese', 'Thimphu', 'AS', 'BTN', 'dz', 'https://restcountries.eu/data/btn.svg', '+975'),
('068', 'BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivian', 'Sucre', 'SA', 'BOB', 'es', 'https://restcountries.eu/data/bol.svg', '+591'),
('070', 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnian, Herzegovinian', 'Sarajevo', 'EU', 'BAM', 'bs', 'https://restcountries.eu/data/bih.svg', '+387'),
('072', 'BW', 'BWA', 'Botswana', 'Motswana, Botswanan', 'Gaborone', 'AF', 'BWP', 'en', 'https://restcountries.eu/data/bwa.svg', '+267'),
('076', 'BR', 'BRA', 'Brazil', 'Brazilian', 'Brasília', 'SA', 'BRL', 'pt', 'https://restcountries.eu/data/bra.svg', '+55'),
('096', 'BN', 'BRN', 'Brunei Darussalam', 'Bruneian', 'Bandar Seri Begawan', 'AS', 'BND', 'ms', 'https://restcountries.eu/data/brn.svg', '+673'),
('100', 'BG', 'BGR', 'Bulgaria', 'Bulgarian', 'Sofia', 'EU', 'BGN', 'bg', 'https://restcountries.eu/data/bgr.svg', '+359'),
('854', 'BF', 'BFA', 'Burkina Faso', 'Burkinabé', 'Ouagadougou', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/bfa.svg', '+226'),
('108', 'BI', 'BDI', 'Burundi', 'Burundian', 'Bujumbura', 'AF', 'BIF', 'fr', 'https://restcountries.eu/data/bdi.svg', '+257'),
('116', 'KH', 'KHM', 'Cambodia', 'Cambodian', 'Phnom Penh', 'AS', 'KHR', 'km', 'https://restcountries.eu/data/khm.svg', '+855'),
('120', 'CM', 'CMR', 'Cameroon', 'Cameroonian', 'Yaoundé', 'AF', 'XAF', 'en', 'https://restcountries.eu/data/cmr.svg', '+237'),
('124', 'CA', 'CAN', 'Canada', 'Canadian', 'Ottawa', 'NA', 'CAD', 'en', 'https://restcountries.eu/data/can.svg', '+1'),
('132', 'CV', 'CPV', 'Cabo Verde', 'Cabo Verdean', 'Praia', 'AF', 'CVE', 'pt', 'https://restcountries.eu/data/cpv.svg', '+238'),
('136', 'KY', 'CYM', 'Cayman Islands', 'Caymanian', 'George Town', 'NA', 'KYD', 'en', 'https://restcountries.eu/data/cym.svg', '+1345'),
('140', 'CF', 'CAF', 'Central African Republic', 'Central African', 'Bangui', 'AF', 'XAF', 'fr', 'https://restcountries.eu/data/caf.svg', '+236'),
('148', 'TD', 'TCD', 'Chad', 'Chadian', 'N''Djamena', 'AF', 'XAF', 'fr', 'https://restcountries.eu/data/tcd.svg', '+235'),
('152', 'CL', 'CHL', 'Chile', 'Chilean', 'Santiago', 'SA', 'CLP', 'es', 'https://restcountries.eu/data/chl.svg', '+56'),
('156', 'CN', 'CHN', 'China', 'Chinese', 'Beijing', 'AS', 'CNY', 'zh', 'https://restcountries.eu/data/chn.svg', '+86'),
('170', 'CO', 'COL', 'Colombia', 'Colombian', 'Bogotá', 'SA', 'COP', 'es', 'https://restcountries.eu/data/col.svg', '+57'),
('174', 'KM', 'COM', 'Comoros', 'Comoran', 'Moroni', 'AF', 'KMF', 'fr', 'https://restcountries.eu/data/com.svg', '+269'),
('178', 'CG', 'COG', 'Congo', 'Congolese', 'Brazzaville', 'AF', 'XAF', 'fr', 'https://restcountries.eu/data/cog.svg', '+242'),
('180', 'CD', 'COD', 'Congo (Democratic Republic of the)', 'Congolese', 'Kinshasa', 'AF', 'CDF', 'fr', 'https://restcountries.eu/data/cod.svg', '+243'),
('188', 'CR', 'CRI', 'Costa Rica', 'Costa Rican', 'San José', 'NA', 'CRC', 'es', 'https://restcountries.eu/data/cri.svg', '+506'),
('384', 'CI', 'CIV', 'Côte d''Ivoire', 'Ivorian', 'Yamoussoukro', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/civ.svg', '+225'),
('191', 'HR', 'HRV', 'Croatia', 'Croatian', 'Zagreb', 'EU', 'HRK', 'hr', 'https://restcountries.eu/data/hrv.svg', '+385'),
('192', 'CU', 'CUB', 'Cuba', 'Cuban', 'Havana', 'NA', 'CUC', 'es', 'https://restcountries.eu/data/cub.svg', '+53'),
('196', 'CY', 'CYP', 'Cyprus', 'Cypriot', 'Nicosia', 'EU', 'EUR', 'el', 'https://restcountries.eu/data/cyp.svg', '+357'),
('203', 'CZ', 'CZE', 'Czech Republic', 'Czech', 'Prague', 'EU', 'CZK', 'cs', 'https://restcountries.eu/data/cze.svg', '+420'),
('208', 'DK', 'DNK', 'Denmark', 'Danish', 'Copenhagen', 'EU', 'DKK', 'da', 'https://restcountries.eu/data/dnk.svg', '+45'),
('262', 'DJ', 'DJI', 'Djibouti', 'Djiboutian', 'Djibouti', 'AF', 'DJF', 'fr', 'https://restcountries.eu/data/dji.svg', '+253'),
('212', 'DM', 'DMA', 'Dominica', 'Dominican', 'Roseau', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/dma.svg', '+1767'),
('214', 'DO', 'DOM', 'Dominican Republic', 'Dominican', 'Santo Domingo', 'NA', 'DOP', 'es', 'https://restcountries.eu/data/dom.svg', '+1809'),
('218', 'EC', 'ECU', 'Ecuador', 'Ecuadorian', 'Quito', 'SA', 'USD', 'es', 'https://restcountries.eu/data/ecu.svg', '+593'),
('818', 'EG', 'EGY', 'Egypt', 'Egyptian', 'Cairo', 'AF', 'EGP', 'ar', 'https://restcountries.eu/data/egy.svg', '+20'),
('222', 'SV', 'SLV', 'El Salvador', 'Salvadoran', 'San Salvador', 'NA', 'USD', 'es', 'https://restcountries.eu/data/slv.svg', '+503'),
('226', 'GQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinean', 'Malabo', 'AF', 'XAF', 'es', 'https://restcountries.eu/data/gnq.svg', '+240'),
('232', 'ER', 'ERI', 'Eritrea', 'Eritrean', 'Asmara', 'AF', 'ERN', 'ti', 'https://restcountries.eu/data/eri.svg', '+291'),
('233', 'EE', 'EST', 'Estonia', 'Estonian', 'Tallinn', 'EU', 'EUR', 'et', 'https://restcountries.eu/data/est.svg', '+372'),
('231', 'ET', 'ETH', 'Ethiopia', 'Ethiopian', 'Addis Ababa', 'AF', 'ETB', 'am', 'https://restcountries.eu/data/eth.svg', '+251'),
('238', 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Falkland Islander', 'Stanley', 'SA', 'FKP', 'en', 'https://restcountries.eu/data/flk.svg', '+500'),
('234', 'FO', 'FRO', 'Faroe Islands', 'Faroese', 'Tórshavn', 'EU', 'DKK', 'fo', 'https://restcountries.eu/data/fro.svg', '+298'),
('242', 'FJ', 'FJI', 'Fiji', 'Fijian', 'Suva', 'OC', 'FJD', 'en', 'https://restcountries.eu/data/fji.svg', '+679'),
('246', 'FI', 'FIN', 'Finland', 'Finnish', 'Helsinki', 'EU', 'EUR', 'fi', 'https://restcountries.eu/data/fin.svg', '+358'),
('250', 'FR', 'FRA', 'France', 'French', 'Paris', 'EU', 'EUR', 'fr', 'https://restcountries.eu/data/fra.svg', '+33'),
('254', 'GF', 'GUF', 'French Guiana', 'French Guianese', 'Cayenne', 'SA', 'EUR', 'fr', 'https://restcountries.eu/data/guf.svg', '+594'),
('258', 'PF', 'PYF', 'French Polynesia', 'French Polynesian', 'Papeetē', 'OC', 'XPF', 'fr', 'https://restcountries.eu/data/pyf.svg', '+689'),
('266', 'GA', 'GAB', 'Gabon', 'Gabonese', 'Libreville', 'AF', 'XAF', 'fr', 'https://restcountries.eu/data/gab.svg', '+241'),
('270', 'GM', 'GMB', 'Gambia', 'Gambian', 'Banjul', 'AF', 'GMD', 'en', 'https://restcountries.eu/data/gmb.svg', '+220'),
('268', 'GE', 'GEO', 'Georgia', 'Georgian', 'Tbilisi', 'AS', 'GEL', 'ka', 'https://restcountries.eu/data/geo.svg', '+995'),
('276', 'DE', 'DEU', 'Germany', 'German', 'Berlin', 'EU', 'EUR', 'de', 'https://restcountries.eu/data/deu.svg', '+49'),
('288', 'GH', 'GHA', 'Ghana', 'Ghanaian', 'Accra', 'AF', 'GHS', 'en', 'https://restcountries.eu/data/gha.svg', '+233'),
('292', 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'EU', 'GIP', 'en', 'https://restcountries.eu/data/gib.svg', '+350'),
('300', 'GR', 'GRC', 'Greece', 'Greek, Hellenic', 'Athens', 'EU', 'EUR', 'el', 'https://restcountries.eu/data/grc.svg', '+30'),
('304', 'GL', 'GRL', 'Greenland', 'Greenlandic', 'Nuuk', 'NA', 'DKK', 'kl', 'https://restcountries.eu/data/grl.svg', '+299'),
('308', 'GD', 'GRD', 'Grenada', 'Grenadian', 'St. George''s', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/grd.svg', '+1473'),
('312', 'GP', 'GLP', 'Guadeloupe', 'Guadeloupian', 'Basse-Terre', 'NA', 'EUR', 'fr', 'https://restcountries.eu/data/glp.svg', '+590'),
('316', 'GU', 'GUM', 'Guam', 'Guamanian', 'Hagåtña', 'OC', 'USD', 'en', 'https://restcountries.eu/data/gum.svg', '+1671'),
('320', 'GT', 'GTM', 'Guatemala', 'Guatemalan', 'Guatemala City', 'NA', 'GTQ', 'es', 'https://restcountries.eu/data/gtm.svg', '+502'),
('324', 'GN', 'GIN', 'Guinea', 'Guinean', 'Conakry', 'AF', 'GNF', 'fr', 'https://restcountries.eu/data/gin.svg', '+224'),
('624', 'GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissauan', 'Bissau', 'AF', 'XOF', 'pt', 'https://restcountries.eu/data/gnb.svg', '+245'),
('328', 'GY', 'GUY', 'Guyana', 'Guyanese', 'Georgetown', 'SA', 'GYD', 'en', 'https://restcountries.eu/data/guy.svg', '+592'),
('332', 'HT', 'HTI', 'Haiti', 'Haitian', 'Port-au-Prince', 'NA', 'HTG', 'fr', 'https://restcountries.eu/data/hti.svg', '+509'),
('340', 'HN', 'HND', 'Honduras', 'Honduran', 'Tegucigalpa', 'NA', 'HNL', 'es', 'https://restcountries.eu/data/hnd.svg', '+504'),
('344', 'HK', 'HKG', 'Hong Kong', 'Hong Kongese', 'City of Victoria', 'AS', 'HKD', 'zh', 'https://restcountries.eu/data/hkg.svg', '+852'),
('348', 'HU', 'HUN', 'Hungary', 'Hungarian', 'Budapest', 'EU', 'HUF', 'hu', 'https://restcountries.eu/data/hun.svg', '+36'),
('352', 'IS', 'ISL', 'Iceland', 'Icelandic', 'Reykjavík', 'EU', 'ISK', 'is', 'https://restcountries.eu/data/isl.svg', '+354'),
('356', 'IN', 'IND', 'India', 'Indian', 'New Delhi', 'AS', 'INR', 'hi', 'https://restcountries.eu/data/ind.svg', '+91'),
('360', 'ID', 'IDN', 'Indonesia', 'Indonesian', 'Jakarta', 'AS', 'IDR', 'id', 'https://restcountries.eu/data/idn.svg', '+62'),
('364', 'IR', 'IRN', 'Iran (Islamic Republic of)', 'Iranian', 'Tehran', 'AS', 'IRR', 'fa', 'https://restcountries.eu/data/irn.svg', '+98'),
('368', 'IQ', 'IRQ', 'Iraq', 'Iraqi', 'Baghdad', 'AS', 'IQD', 'ar', 'https://restcountries.eu/data/irq.svg', '+964'),
('372', 'IE', 'IRL', 'Ireland', 'Irish', 'Dublin', 'EU', 'EUR', 'ga', 'https://restcountries.eu/data/irl.svg', '+353'),
('376', 'IL', 'ISR', 'Israel', 'Israeli', 'Jerusalem', 'AS', 'ILS', 'he', 'https://restcountries.eu/data/isr.svg', '+972'),
('380', 'IT', 'ITA', 'Italy', 'Italian', 'Rome', 'EU', 'EUR', 'it', 'https://restcountries.eu/data/ita.svg', '+39'),
('388', 'JM', 'JAM', 'Jamaica', 'Jamaican', 'Kingston', 'NA', 'JMD', 'en', 'https://restcountries.eu/data/jam.svg', '+1876'),
('392', 'JP', 'JPN', 'Japan', 'Japanese', 'Tokyo', 'AS', 'JPY', 'ja', 'https://restcountries.eu/data/jpn.svg', '+81'),
('400', 'JO', 'JOR', 'Jordan', 'Jordanian', 'Amman', 'AS', 'JOD', 'ar', 'https://restcountries.eu/data/jor.svg', '+962'),
('398', 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstani', 'Astana', 'AS', 'KZT', 'kk', 'https://restcountries.eu/data/kaz.svg', '+7'),
('404', 'KE', 'KEN', 'Kenya', 'Kenyan', 'Nairobi', 'AF', 'KES', 'en', 'https://restcountries.eu/data/ken.svg', '+254'),
('296', 'KI', 'KIR', 'Kiribati', 'I-Kiribati', 'South Tarawa', 'OC', 'AUD', 'en', 'https://restcountries.eu/data/kir.svg', '+686'),
('408', 'KP', 'PRK', 'Korea (Democratic People''s Republic of)', 'North Korean', 'Pyongyang', 'AS', 'KPW', 'ko', 'https://restcountries.eu/data/prk.svg', '+850'),
('410', 'KR', 'KOR', 'Korea (Republic of)', 'South Korean', 'Seoul', 'AS', 'KRW', 'ko', 'https://restcountries.eu/data/kor.svg', '+82'),
('414', 'KW', 'KWT', 'Kuwait', 'Kuwaiti', 'Kuwait City', 'AS', 'KWD', 'ar', 'https://restcountries.eu/data/kwt.svg', '+965'),
('417', 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyz', 'Bishkek', 'AS', 'KGS', 'ky', 'https://restcountries.eu/data/kgz.svg', '+996'),
('418', 'LA', 'LAO', 'Lao People''s Democratic Republic', 'Lao', 'Vientiane', 'AS', 'LAK', 'lo', 'https://restcountries.eu/data/lao.svg', '+856'),
('428', 'LV', 'LVA', 'Latvia', 'Latvian', 'Riga', 'EU', 'EUR', 'lv', 'https://restcountries.eu/data/lva.svg', '+371'),
('422', 'LB', 'LBN', 'Lebanon', 'Lebanese', 'Beirut', 'AS', 'LBP', 'ar', 'https://restcountries.eu/data/lbn.svg', '+961'),
('426', 'LS', 'LSO', 'Lesotho', 'Basotho', 'Maseru', 'AF', 'LSL', 'en', 'https://restcountries.eu/data/lso.svg', '+266'),
('430', 'LR', 'LBR', 'Liberia', 'Liberian', 'Monrovia', 'AF', 'LRD', 'en', 'https://restcountries.eu/data/lbr.svg', '+231'),
('434', 'LY', 'LBY', 'Libya', 'Libyan', 'Tripoli', 'AF', 'LYD', 'ar', 'https://restcountries.eu/data/lby.svg', '+218'),
('438', 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Vaduz', 'EU', 'CHF', 'de', 'https://restcountries.eu/data/lie.svg', '+423'),
('440', 'LT', 'LTU', 'Lithuania', 'Lithuanian', 'Vilnius', 'EU', 'EUR', 'lt', 'https://restcountries.eu/data/ltu.svg', '+370'),
('442', 'LU', 'LUX', 'Luxembourg', 'Luxembourgish', 'Luxembourg', 'EU', 'EUR', 'fr', 'https://restcountries.eu/data/lux.svg', '+352'),
('446', 'MO', 'MAC', 'Macao', 'Macanese', 'Macao', 'AS', 'MOP', 'zh', 'https://restcountries.eu/data/mac.svg', '+853'),
('807', 'MK', 'MKD', 'Macedonia (the former Yugoslav Republic of)', 'Macedonian', 'Skopje', 'EU', 'MKD', 'mk', 'https://restcountries.eu/data/mkd.svg', '+389'),
('450', 'MG', 'MDG', 'Madagascar', 'Malagasy', 'Antananarivo', 'AF', 'MGA', 'fr', 'https://restcountries.eu/data/mdg.svg', '+261'),
('454', 'MW', 'MWI', 'Malawi', 'Malawian', 'Lilongwe', 'AF', 'MWK', 'en', 'https://restcountries.eu/data/mwi.svg', '+265'),
('458', 'MY', 'MYS', 'Malaysia', 'Malaysian', 'Kuala Lumpur', 'AS', 'MYR', 'ms', 'https://restcountries.eu/data/mys.svg', '+60'),
('462', 'MV', 'MDV', 'Maldives', 'Maldivian', 'Malé', 'AS', 'MVR', 'dv', 'https://restcountries.eu/data/mdv.svg', '+960'),
('466', 'ML', 'MLI', 'Mali', 'Malian', 'Bamako', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/mli.svg', '+223'),
('470', 'MT', 'MLT', 'Malta', 'Maltese', 'Valletta', 'EU', 'EUR', 'mt', 'https://restcountries.eu/data/mlt.svg', '+356'),
('584', 'MH', 'MHL', 'Marshall Islands', 'Marshallese', 'Majuro', 'OC', 'USD', 'en', 'https://restcountries.eu/data/mhl.svg', '+692'),
('474', 'MQ', 'MTQ', 'Martinique', 'Martinican', 'Fort-de-France', 'NA', 'EUR', 'fr', 'https://restcountries.eu/data/mtq.svg', '+596'),
('478', 'MR', 'MRT', 'Mauritania', 'Mauritanian', 'Nouakchott', 'AF', 'MRO', 'ar', 'https://restcountries.eu/data/mrt.svg', '+222'),
('480', 'MU', 'MUS', 'Mauritius', 'Mauritian', 'Port Louis', 'AF', 'MUR', 'en', 'https://restcountries.eu/data/mus.svg', '+230'),
('175', 'YT', 'MYT', 'Mayotte', 'Mahoran', 'Mamoudzou', 'AF', 'EUR', 'fr', 'https://restcountries.eu/data/myt.svg', '+262'),
('484', 'MX', 'MEX', 'Mexico', 'Mexican', 'Mexico City', 'NA', 'MXN', 'es', 'https://restcountries.eu/data/mex.svg', '+52'),
('583', 'FM', 'FSM', 'Micronesia (Federated States of)', 'Micronesian', 'Palikir', 'OC', 'USD', 'en', 'https://restcountries.eu/data/fsm.svg', '+691'),
('498', 'MD', 'MDA', 'Moldova (Republic of)', 'Moldovan', 'Chișinău', 'EU', 'MDL', 'ro', 'https://restcountries.eu/data/mda.svg', '+373'),
('492', 'MC', 'MCO', 'Monaco', 'Monégasque', 'Monaco', 'EU', 'EUR', 'fr', 'https://restcountries.eu/data/mco.svg', '+377'),
('496', 'MN', 'MNG', 'Mongolia', 'Mongolian', 'Ulan Bator', 'AS', 'MNT', 'mn', 'https://restcountries.eu/data/mng.svg', '+976'),
('499', 'ME', 'MNE', 'Montenegro', 'Montenegrin', 'Podgorica', 'EU', 'EUR', 'sr', 'https://restcountries.eu/data/mne.svg', '+382'),
('500', 'MS', 'MSR', 'Montserrat', 'Montserratian', 'Plymouth', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/msr.svg', '+1664'),
('504', 'MA', 'MAR', 'Morocco', 'Moroccan', 'Rabat', 'AF', 'MAD', 'ar', 'https://restcountries.eu/data/mar.svg', '+212'),
('508', 'MZ', 'MOZ', 'Mozambique', 'Mozambican', 'Maputo', 'AF', 'MZN', 'pt', 'https://restcountries.eu/data/moz.svg', '+258'),
('104', 'MM', 'MMR', 'Myanmar', 'Burmese', 'Naypyidaw', 'AS', 'MMK', 'my', 'https://restcountries.eu/data/mmr.svg', '+95'),
('516', 'NA', 'NAM', 'Namibia', 'Namibian', 'Windhoek', 'AF', 'NAD', 'en', 'https://restcountries.eu/data/nam.svg', '+264'),
('520', 'NR', 'NRU', 'Nauru', 'Nauruan', 'Yaren', 'OC', 'AUD', 'en', 'https://restcountries.eu/data/nru.svg', '+674'),
('524', 'NP', 'NPL', 'Nepal', 'Nepalese', 'Kathmandu', 'AS', 'NPR', 'ne', 'https://restcountries.eu/data/npl.svg', '+977'),
('528', 'NL', 'NLD', 'Netherlands', 'Dutch', 'Amsterdam', 'EU', 'EUR', 'nl', 'https://restcountries.eu/data/nld.svg', '+31'),
('540', 'NC', 'NCL', 'New Caledonia', 'New Caledonian', 'Nouméa', 'OC', 'XPF', 'fr', 'https://restcountries.eu/data/ncl.svg', '+687'),
('554', 'NZ', 'NZL', 'New Zealand', 'New Zealander', 'Wellington', 'OC', 'NZD', 'en', 'https://restcountries.eu/data/nzl.svg', '+64'),
('558', 'NI', 'NIC', 'Nicaragua', 'Nicaraguan', 'Managua', 'NA', 'NIO', 'es', 'https://restcountries.eu/data/nic.svg', '+505'),
('562', 'NE', 'NER', 'Niger', 'Nigerien', 'Niamey', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/ner.svg', '+227'),
('566', 'NG', 'NGA', 'Nigeria', 'Nigerian', 'Abuja', 'AF', 'NGN', 'en', 'https://restcountries.eu/data/nga.svg', '+234'),
('570', 'NU', 'NIU', 'Niue', 'Niuean', 'Alofi', 'OC', 'NZD', 'en', 'https://restcountries.eu/data/niu.svg', '+683'),
('574', 'NF', 'NFK', 'Norfolk Island', 'Norfolk Islander', 'Kingston', 'OC', 'AUD', 'en', 'https://restcountries.eu/data/nfk.svg', '+672'),
('580', 'MP', 'MNP', 'Northern Mariana Islands', 'Northern Marianan', 'Saipan', 'OC', 'USD', 'en', 'https://restcountries.eu/data/mnp.svg', '+1670'),
('578', 'NO', 'NOR', 'Norway', 'Norwegian', 'Oslo', 'EU', 'NOK', 'no', 'https://restcountries.eu/data/nor.svg', '+47'),
('512', 'OM', 'OMN', 'Oman', 'Omani', 'Muscat', 'AS', 'OMR', 'ar', 'https://restcountries.eu/data/omn.svg', '+968'),
('586', 'PK', 'PAK', 'Pakistan', 'Pakistani', 'Islamabad', 'AS', 'PKR', 'en', 'https://restcountries.eu/data/pak.svg', '+92'),
('585', 'PW', 'PLW', 'Palau', 'Palauan', 'Ngerulmud', 'OC', 'USD', 'en', 'https://restcountries.eu/data/plw.svg', '+680'),
('275', 'PS', 'PSE', 'Palestine, State of', 'Palestinian', 'Ramallah', 'AS', 'ILS', 'ar', 'https://restcountries.eu/data/pse.svg', '+970'),
('591', 'PA', 'PAN', 'Panama', 'Panamanian', 'Panama City', 'NA', 'PAB', 'es', 'https://restcountries.eu/data/pan.svg', '+507'),
('598', 'PG', 'PNG', 'Papua New Guinea', 'Papua New Guinean', 'Port Moresby', 'OC', 'PGK', 'en', 'https://restcountries.eu/data/png.svg', '+675'),
('600', 'PY', 'PRY', 'Paraguay', 'Paraguayan', 'Asunción', 'SA', 'PYG', 'es', 'https://restcountries.eu/data/pry.svg', '+595'),
('604', 'PE', 'PER', 'Peru', 'Peruvian', 'Lima', 'SA', 'PEN', 'es', 'https://restcountries.eu/data/per.svg', '+51'),
('608', 'PH', 'PHL', 'Philippines', 'Filipino', 'Manila', 'AS', 'PHP', 'en', 'https://restcountries.eu/data/phl.svg', '+63'),
('612', 'PN', 'PCN', 'Pitcairn', 'Pitcairn Islander', 'Adamstown', 'OC', 'NZD', 'en', 'https://restcountries.eu/data/pcn.svg', '+64'),
('616', 'PL', 'POL', 'Poland', 'Polish', 'Warsaw', 'EU', 'PLN', 'pl', 'https://restcountries.eu/data/pol.svg', '+48'),
('620', 'PT', 'PRT', 'Portugal', 'Portuguese', 'Lisbon', 'EU', 'EUR', 'pt', 'https://restcountries.eu/data/prt.svg', '+351'),
('630', 'PR', 'PRI', 'Puerto Rico', 'Puerto Rican', 'San Juan', 'NA', 'USD', 'es', 'https://restcountries.eu/data/pri.svg', '+1787'),
('634', 'QA', 'QAT', 'Qatar', 'Qatari', 'Doha', 'AS', 'QAR', 'ar', 'https://restcountries.eu/data/qat.svg', '+974'),
('638', 'RE', 'REU', 'Réunion', 'Réunionese', 'Saint-Denis', 'AF', 'EUR', 'fr', 'https://restcountries.eu/data/reu.svg', '+262'),
('642', 'RO', 'ROU', 'Romania', 'Romanian', 'Bucharest', 'EU', 'RON', 'ro', 'https://restcountries.eu/data/rou.svg', '+40'),
('643', 'RU', 'RUS', 'Russian Federation', 'Russian', 'Moscow', 'EU', 'RUB', 'ru', 'https://restcountries.eu/data/rus.svg', '+7'),
('646', 'RW', 'RWA', 'Rwanda', 'Rwandan', 'Kigali', 'AF', 'RWF', 'rw', 'https://restcountries.eu/data/rwa.svg', '+250'),
('652', 'BL', 'BLM', 'Saint Barthélemy', 'Saint Barthélemy Islander', 'Gustavia', 'NA', 'EUR', 'fr', 'https://restcountries.eu/data/blm.svg', '+590'),
('654', 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian', 'Jamestown', 'AF', 'SHP', 'en', 'https://restcountries.eu/data/shn.svg', '+290'),
('659', 'KN', 'KNA', 'Saint Kitts and Nevis', 'Kittian and Nevisian', 'Basseterre', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/kna.svg', '+1869'),
('662', 'LC', 'LCA', 'Saint Lucia', 'Saint Lucian', 'Castries', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/lca.svg', '+1758'),
('663', 'MF', 'MAF', 'Saint Martin (French part)', 'Saint Martin Islander', 'Marigot', 'NA', 'EUR', 'en', 'https://restcountries.eu/data/maf.svg', '+590'),
('666', 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierrais, Miquelonnais', 'Saint-Pierre', 'NA', 'EUR', 'fr', 'https://restcountries.eu/data/spm.svg', '+508'),
('670', 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincentian', 'Kingstown', 'NA', 'XCD', 'en', 'https://restcountries.eu/data/vct.svg', '+1784'),
('882', 'WS', 'WSM', 'Samoa', 'Samoan', 'Apia', 'OC', 'WST', 'sm', 'https://restcountries.eu/data/wsm.svg', '+685'),
('674', 'SM', 'SMR', 'San Marino', 'Sammarinese', 'City of San Marino', 'EU', 'EUR', 'it', 'https://restcountries.eu/data/smr.svg', '+378'),
('678', 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomean', 'São Tomé', 'AF', 'STD', 'pt', 'https://restcountries.eu/data/stp.svg', '+239'),
('682', 'SA', 'SAU', 'Saudi Arabia', 'Saudi Arabian', 'Riyadh', 'AS', 'SAR', 'ar', 'https://restcountries.eu/data/sau.svg', '+966'),
('686', 'SN', 'SEN', 'Senegal', 'Senegalese', 'Dakar', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/sen.svg', '+221'),
('688', 'RS', 'SRB', 'Serbia', 'Serbian', 'Belgrade', 'EU', 'RSD', 'sr', 'https://restcountries.eu/data/srb.svg', '+381'),
('690', 'SC', 'SYC', 'Seychelles', 'Seychellois', 'Victoria', 'AF', 'SCR', 'fr', 'https://restcountries.eu/data/syc.svg', '+248'),
('694', 'SL', 'SLE', 'Sierra Leone', 'Sierra Leonean', 'Freetown', 'AF', 'SLL', 'en', 'https://restcountries.eu/data/sle.svg', '+232'),
('702', 'SG', 'SGP', 'Singapore', 'Singaporean', 'Singapore', 'AS', 'SGD', 'en', 'https://restcountries.eu/data/sgp.svg', '+65'),
('534', 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten', 'Philipsburg', 'NA', 'ANG', 'nl', 'https://restcountries.eu/data/sxm.svg', '+1721'),
('703', 'SK', 'SVK', 'Slovakia', 'Slovak', 'Bratislava', 'EU', 'EUR', 'sk', 'https://restcountries.eu/data/svk.svg', '+421'),
('705', 'SI', 'SVN', 'Slovenia', 'Slovene', 'Ljubljana', 'EU', 'EUR', 'sl', 'https://restcountries.eu/data/svn.svg', '+386'),
('090', 'SB', 'SLB', 'Solomon Islands', 'Solomon Islander', 'Honiara', 'OC', 'SBD', 'en', 'https://restcountries.eu/data/slb.svg', '+677'),
('706', 'SO', 'SOM', 'Somalia', 'Somali', 'Mogadishu', 'AF', 'SOS', 'ar', 'https://restcountries.eu/data/som.svg', '+252'),
('710', 'ZA', 'ZAF', 'South Africa', 'South African', 'Pretoria', 'AF', 'ZAR', 'en', 'https://restcountries.eu/data/zaf.svg', '+27'),
('239', 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islander', 'King Edward Point', 'AN', 'GBP', 'en', 'https://restcountries.eu/data/sgs.svg', '+500'),
('728', 'SS', 'SSD', 'South Sudan', 'South Sudanese', 'Juba', 'AF', 'SSP', 'en', 'https://restcountries.eu/data/ssd.svg', '+211'),
('724', 'ES', 'ESP', 'Spain', 'Spanish', 'Madrid', 'EU', 'EUR', 'es', 'https://restcountries.eu/data/esp.svg', '+34'),
('144', 'LK', 'LKA', 'Sri Lanka', 'Sri Lankan', 'Colombo', 'AS', 'LKR', 'si', 'https://restcountries.eu/data/lka.svg', '+94'),
('729', 'SD', 'SDN', 'Sudan', 'Sudanese', 'Khartoum', 'AF', 'SDG', 'ar', 'https://restcountries.eu/data/sdn.svg', '+249'),
('740', 'SR', 'SUR', 'Suriname', 'Surinamese', 'Paramaribo', 'SA', 'SRD', 'nl', 'https://restcountries.eu/data/sur.svg', '+597'),
('744', 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Norwegian', 'Longyearbyen', 'EU', 'NOK', 'no', 'https://restcountries.eu/data/sjm.svg', '+47'),
('748', 'SZ', 'SWZ', 'Swaziland', 'Swazi', 'Lobamba', 'AF', 'SZL', 'en', 'https://restcountries.eu/data/swz.svg', '+268'),
('752', 'SE', 'SWE', 'Sweden', 'Swedish', 'Stockholm', 'EU', 'SEK', 'sv', 'https://restcountries.eu/data/swe.svg', '+46'),
('756', 'CH', 'CHE', 'Switzerland', 'Swiss', 'Bern', 'EU', 'CHF', 'de', 'https://restcountries.eu/data/che.svg', '+41'),
('760', 'SY', 'SYR', 'Syrian Arab Republic', 'Syrian', 'Damascus', 'AS', 'SYP', 'ar', 'https://restcountries.eu/data/syr.svg', '+963'),
('158', 'TW', 'TWN', 'Taiwan', 'Taiwanese', 'Taipei', 'AS', 'TWD', 'zh', 'https://restcountries.eu/data/twn.svg', '+886'),
('762', 'TJ', 'TJK', 'Tajikistan', 'Tajik', 'Dushanbe', 'AS', 'TJS', 'tg', 'https://restcountries.eu/data/tjk.svg', '+992'),
('834', 'TZ', 'TZA', 'Tanzania, United Republic of', 'Tanzanian', 'Dodoma', 'AF', 'TZS', 'en', 'https://restcountries.eu/data/tza.svg', '+255'),
('764', 'TH', 'THA', 'Thailand', 'Thai', 'Bangkok', 'AS', 'THB', 'th', 'https://restcountries.eu/data/tha.svg', '+66'),
('626', 'TL', 'TLS', 'Timor-Leste', 'East Timorese', 'Dili', 'AS', 'USD', 'pt', 'https://restcountries.eu/data/tls.svg', '+670'),
('768', 'TG', 'TGO', 'Togo', 'Togolese', 'Lomé', 'AF', 'XOF', 'fr', 'https://restcountries.eu/data/tgo.svg', '+228'),
('772', 'TK', 'TKL', 'Tokelau', 'Tokelauan', 'Fakaofo', 'OC', 'NZD', 'en', 'https://restcountries.eu/data/tkl.svg', '+690'),
('776', 'TO', 'TON', 'Tonga', 'Tongan', 'Nuku''alofa', 'OC', 'TOP', 'en', 'https://restcountries.eu/data/ton.svg', '+676'),
('780', 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidadian', 'Port of Spain', 'SA', 'TTD', 'en', 'https://restcountries.eu/data/tto.svg', '+1868'),
('788', 'TN', 'TUN', 'Tunisia', 'Tunisian', 'Tunis', 'AF', 'TND', 'ar', 'https://restcountries.eu/data/tun.svg', '+216'),
('792', 'TR', 'TUR', 'Turkey', 'Turkish', 'Ankara', 'AS', 'TRY', 'tr', 'https://restcountries.eu/data/tur.svg', '+90'),
('795', 'TM', 'TKM', 'Turkmenistan', 'Turkmen', 'Ashgabat', 'AS', 'TMT', 'tk', 'https://restcountries.eu/data/tkm.svg', '+993'),
('796', 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islander', 'Cockburn Town', 'NA', 'USD', 'en', 'https://restcountries.eu/data/tca.svg', '+1649'),
('798', 'TV', 'TUV', 'Tuvalu', 'Tuvaluan', 'Funafuti', 'OC', 'AUD', 'en', 'https://restcountries.eu/data/tuv.svg', '+688'),
('800', 'UG', 'UGA', 'Uganda', 'Ugandan', 'Kampala', 'AF', 'UGX', 'en', 'https://restcountries.eu/data/uga.svg', '+256'),
('804', 'UA', 'UKR', 'Ukraine', 'Ukrainian', 'Kyiv', 'EU', 'UAH', 'uk', 'https://restcountries.eu/data/ukr.svg', '+380'),
('784', 'AE', 'ARE', 'United Arab Emirates', 'Emirati', 'Abu Dhabi', 'AS', 'AED', 'ar', 'https://restcountries.eu/data/are.svg', '+971'),
('826', 'GB', 'GBR', 'United Kingdom of Great Britain and Northern Ireland', 'British', 'London', 'EU', 'GBP', 'en', 'https://restcountries.eu/data/gbr.svg', '+44'),
('840', 'US', 'USA', 'United States of America', 'American', 'Washington, D.C.', 'NA', 'USD', 'en', 'https://restcountries.eu/data/usa.svg', '+1'),
('858', 'UY', 'URY', 'Uruguay', 'Uruguayan', 'Montevideo', 'SA', 'UYU', 'es', 'https://restcountries.eu/data/ury.svg', '+598'),
('860', 'UZ', 'UZB', 'Uzbekistan', 'Uzbekistani', 'Tashkent', 'AS', 'UZS', 'uz', 'https://restcountries.eu/data/uzb.svg', '+998'),
('548', 'VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu', 'Port Vila', 'OC', 'VUV', 'en', 'https://restcountries.eu/data/vut.svg', '+678'),
('862', 'VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuelan', 'Caracas', 'SA', 'VEF', 'es', 'https://restcountries.eu/data/ven.svg', '+58'),
('704', 'VN', 'VNM', 'Viet Nam', 'Vietnamese', 'Hanoi', 'AS', 'VND', 'vi', 'https://restcountries.eu/data/vnm.svg', '+84'),
('876', 'WF', 'WLF', 'Wallis and Futuna', 'Wallis and Futuna Islander', 'Mata-Utu', 'OC', 'XPF', 'fr', 'https://restcountries.eu/data/wlf.svg', '+681'),
('732', 'EH', 'ESH', 'Western Sahara', 'Sahrawi', 'El Aaiún', 'AF', 'MAD', 'es', 'https://restcountries.eu/data/esh.svg', '+212'),
('887', 'YE', 'YEM', 'Yemen', 'Yemeni', 'Sana''a', 'AS', 'YER', 'ar', 'https://restcountries.eu/data/yem.svg', '+967'),
('894', 'ZM', 'ZMB', 'Zambia', 'Zambian', 'Lusaka', 'AF', 'ZMW', 'en', 'https://restcountries.eu/data/zmb.svg', '+260'),
('716', 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean', 'Harare', 'AF', 'BWP', 'en', 'https://restcountries.eu/data/zwe.svg', '+263');
